#!/bin/bash

echo "PRIOR_VERSION=" >> $GITHUB_ENV
echo "NEXT_VERSION=" >> $GITHUB_ENV
echo "NEXT_MINOR_VERSION=" >> $GITHUB_ENV
echo "NEXT_MAJOR_VERSION=" >> $GITHUB_ENV
echo "PRIOR_VERSION_NO_PREFIX=" >> $GITHUB_ENV
echo "NEXT_VERSION_NO_PREFIX=" >> $GITHUB_ENV
echo "NEXT_MINOR_VERSION_NO_PREFIX=" >> $GITHUB_ENV
echo "NEXT_MAJOR_VERSION_NO_PREFIX=" >> $GITHUB_ENV